{
    "id": "sample3",
    "segmentID": "default",
    "layout": "11",
    "language": "ENU",
	"passage": {"bankKey":1,"itemKey":100,"printed":false,"filePath":null,"resources":{},"attachments":[],"media":[],"specs":[]},
    "items": [{
        "bankKey": 1,
        "itemKey": 1,
        "subject": "Reading",
        "grade": "11",
        "format": "ER",
        "disabled": false,
        "responseType": "HTMLEditor",
        "position": 1,
        "positionOnPage": 1,
        "filePath": null,
        "printed": false,
        "tutorial": {
            "bankKey": 196,
            "itemKey": 314
        },
        "resources": {},
        "attachments": [],
        "media": [],
        "rendererSpec": null,
        "gridAnswerSpace": null,
        "value": null,
        "specs": []
    }, {
        "bankKey": 1,
        "itemKey": 2,
        "subject": "Reading",
        "grade": "11",
        "format": "ER",
        "disabled": false,
        "responseType": "HTMLEditor",
        "position": 2,
        "positionOnPage": 2,
        "filePath": null,
        "printed": false,
        "tutorial": {
            "bankKey": 196,
            "itemKey": 314
        },
        "resources": {},
        "attachments": [],
        "media": [],
        "rendererSpec": null,
        "gridAnswerSpace": null,
        "value": null,
        "specs": []
    },
	{
        "bankKey": 1,
        "itemKey": 3,
        "subject": "Reading",
        "grade": "11",
        "format": "ER",
        "disabled": false,
        "responseType": "HTMLEditor",
        "position": 3,
        "positionOnPage": 3,
        "filePath": null,
        "printed": false,
        "tutorial": {
            "bankKey": 196,
            "itemKey": 314
        },
        "resources": {},
        "attachments": [],
        "media": [],
        "rendererSpec": null,
        "gridAnswerSpace": null,
        "value": null,
        "specs": []
    }, {
        "bankKey": 1,
        "itemKey": 4,
        "subject": "Reading",
        "grade": "11",
        "format": "ER",
        "disabled": false,
        "responseType": "HTMLEditor",
        "position": 4,
        "positionOnPage": 4,
        "filePath": null,
        "printed": false,
        "tutorial": {
            "bankKey": 196,
            "itemKey": 314
        },
        "resources": {},
        "attachments": [],
        "media": [],
        "rendererSpec": null,
        "gridAnswerSpace": null,
        "value": null,
        "specs": []
    }],
    "html": "<div id=\"Page_sample3\"><div id=\"Passage_1\" class=\"thePassage\">Passage</div><div id=\"Item_1\" class=\"itemContainer\">ITEM 1</div><div id=\"Item_2\" class=\"itemContainer\">ITEM 2</div><div id=\"Item_3\" class=\"itemContainer\">ITEM 3</div><div id=\"Item_4\" class=\"itemContainer\">ITEM 4</div></div>"
}